# Generated by Django 3.1.4 on 2020-12-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_archieve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='archieve',
            field=models.BooleanField(default=False),
        ),
    ]
